// <auto-generated />
using System;
using Api.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Models.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Campeonato");
                });

            modelBuilder.Entity("Api.Models.Jogadores", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Idade");

                    b.Property<string>("Nome");

                    b.Property<string>("Posicao");

                    b.Property<Guid>("TimeId");

                    b.Property<Guid?>("TimesId");

                    b.Property<bool>("Titular");

                    b.HasKey("Id");

                    b.HasIndex("TimesId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("Api.Models.Times", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CampeonatoId");

                    b.Property<string>("Escudo");

                    b.Property<string>("Nome");

                    b.Property<int>("Pontos");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("Api.Models.Jogadores", b =>
                {
                    b.HasOne("Api.Models.Times")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimesId");
                });

            modelBuilder.Entity("Api.Models.Times", b =>
                {
                    b.HasOne("Api.Models.Campeonato")
                        .WithMany("Times")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
